app_name: sample-app
replicas: 1
service_type: NodePort
container_port: 3000
service_port: 3000
image: node:18-alpine   # <<< REQUIRED
command: ["node", "server.js"]  # <<< REQUIRED FOR NODE APPS

env:
  NODE_ENV: "production"
  PORT: "3000"